@startuml

entity "ユーザー" as user {
  + user_id : ユーザーID
  --
  email : メールアドレス
  password : パスワード
  nickname : ユーザー名
  profile_image_path : プロフィール画像パス
  introduce : 自己紹介文
  active_shipping_address_id : アクティブ配送先ID
  name : 氏名
  name_kana : 氏名カナ
  birthday : 生年月日
  address : 住所
  point : ポイント
}

entity "配送先" as shipping_address {
  + shipping_address_id : 配送先ID
  --
  user_id : ユーザーID
  sei : 姓
  mei : 名
  sei_kana : セイ
  mei_kana : メイ
  post_code : 郵便番号
  prefectures : 都道府県
  municipalities : 市区町村
  street : 番地
  building_name : 建物名
  tel : 電話番号
}

entity "検索履歴" as search_history {
  + search_history_id : ID
  --
  user_id : ユーザーID
  keyword : キーワード
  datetime : 検索日時
}

entity "取引" as transaction {
  + transaction_id : 取引ID
  --
  buyer_id : 購入者ID
  seller_id : 出品者ID
  product_id : 商品ID
  transaction_status_id : 取引ステータスID
  amount : 取引金額
  datetime : 取引日時
}

entity "ポイント" as point {
  + point_id : ポイントID
  --
  user_id : ユーザーID
  transaction_id : 取引ID
  variable_point : 変動ポイント
  is_plus : プラスかどうか
  datetime : 取引日時
}

entity "お気に入り" as favorite {
  + product_id : 商品ID
  + user_id : ユーザーID
  --
  datetime : 登録日時
}

entity "閲覧" as productviews {
  + product_id : 商品ID
  + user_id : ユーザーID
  --
  datetime : 閲覧日時
}

entity "チャージ" as charge {
  + charge_id : チャージID
  --
  user_id : ユーザーID
  point : チャージポイント
  datetime : チャージ日時
}

entity "レビュー" as review {
  + review_id : レビューID
  --
  product_id : 商品ID
  buyer_id : 購入者ID
  usage_duration_id : 使用期間ID
  comment : 使用感コメント
  datetime : レビュー日時
}

entity "商品" as product {
  + product_id : 商品ID
  --
  seller_id : 出品者ID
  age_id : 月齢ID
  weight_id : 体重ID
  height_id : 身長ID
  major_category_id : 大カテゴリID
  minor_category_id : 小カテゴリID
  bland_id : ブランドID
  color_id : 色ID
  product_condition_id : 商品の状態ID
  shipping_fee_responsibility_id : 配送料の負担ID
  shipping_method_id : 配送の方法ID
  shipping_origin_region_id : 配送元の地域ID
  day_to_ship_id : 発送までの日数ID
  status_id : ステータスID
  product_name : 商品名
  product_description : 商品説明
  price : 販売価格
  datetime : 出品日時
}

entity "商品画像" as product_image {
  + product_image_id : 画像ID
  + product_id : 商品ID
  --
  path : 画像パス
  order : 並び順
}

entity "評価" as evaluation {
  + evalution_id : 評価ID
  --
  transaction_id : 取引ID
  evaluator_id : 評価者ID
  evaluatee_id : 被評価者ID
  is_seller : 出品者かどうか
  comment : 評価コメント
  score : 評価値
  datetime : 評価日時
}

entity "お知らせ" as notice {
  + notice_id : ID
  --
  user_id : ユーザーID
  transaction_id : 取引ID
  type_id : 通知のタイプID
  notice_status_id : 通知ステータスID
  datetime : 通知日時
}

entity "大カテゴリ" as major_category {
  + major_category_id : ID
  --
  major_category : 大カテゴリ
}

entity "小カテゴリ" as minor_category {
  + minor_category_id : ID
  --
  major_category_id : 大カテゴリID
  minor_category : 小カテゴリ
}

entity "色" as color {
  + color_id : 色ID
  --
  name : 色名
  color_code : 色コード
}

entity "コードマスタ" as code_master {
  + code_id : コードID
  --
  table : テーブル
  name : ネーム
}

user "1" -- "0..*" shipping_address
user "1" -- "0..*" product
user "1" -- "0..*" transaction
product "1" -- "0..*" transaction
product "1" -- "1..10" product_image
user "1" -- "0..*" search_history
user "1" -- "0..*" point
transaction "1" -- "0..*" point
product "1" -- "0..*" favorite
user "1" -- "0..*" favorite
product "1" -- "0..*" productviews
user "1" -- "0..*" productviews
user "1" -- "0..*" charge
product "1" -- "0..*" review
user "1" -- "0..*" review
major_category "1" -- "0..*" product
minor_category "1" -- "0..*" product
color "1" -- "0..*" product
transaction "1" -- "0..*" evaluation
user "1" -- "0..*" evaluation
major_category "1" -- "0..*" minor_category
user "1" -- "0..*" notice
transaction "1" -- "0..*" notice
product "1" -- "0..*" notice
product -- code_master
user -- code_master
transaction -- code_master
review -- code_master
notice -- code_master
@enduml